cask_args appdir: '/Applications'
tap 'caskroom/cask'
brew 'cask'
brew 'emacs'
brew 'hub'
brew 'rbenv'
brew 'ruby-build'
brew 'ack'
cask 'google-drive'
cask 'iterm2'
cask 'shiftit'
cask 'flycut'
cask 'cryptomator'
cask 'aerial'
cask 'spotify'