#!/bin/sh

# Unix
alias ll="ls -lha"
alias flushdns='dscacheutil -flushcache'
alias tmuxcopy='tmux show-buffer | pbcopy'
alias e='emacsclient'

# Repeat a command multiple times
function repeat() {
  if [[ $1 == "--help" || $1 == "-h" || $1 == "" ]]; then
    echo "Usage: repeat <n-times> <command>"
  else
    n=$1
    shift
    while [ $(( n -= 1 )) -ge 0 ]
    do
      "$@"
    done
  fi
}

# Bundler
alias be="bundle exec"
alias bi="bundle install"

# gem
alias gemi='gem install --no-rdoc --no-ri'

# git
alias gl='git log'
alias gs='git status'
alias gsp='git smart-pull'
alias gd='git diff'
alias gdc='git diff --cached'
alias gap='git add -p'
alias gc='git commit'

# setup
setup() {
  gemi git-smart simple-git-pair rbenv-rehash teamocil
  brew install wemux
}

z() {
  cd ~/Documents/projects/zest/$1
}

f() {
  cd ~/Documents/projects/fsproru/$1
}

# vim ft=sh
