#!/bin/sh

# Unix
alias ll="ls -lha"
alias flushdns='dscacheutil -flushcache'
alias tmuxcopy='tmux show-buffer | pbcopy'
alias e='emacsclient --no-wait'
function mcd () { mkdir -p "$@" && cd "$_"; }

# Bundler
alias be="bundle exec"
alias bi="bundle install"

# gem
alias gemi='gem install --no-rdoc --no-ri'

# git
alias gl='git log'
alias gs='git status'
alias gsp='git smart-pull'
alias gd='git diff'
alias gdc='git diff --cached'
alias gap='git add -p'
alias gc='git commit'

# Alias git to hub
alias git=hub

# Code highlighting
alias highlight_pastebuffer='pbpaste | highlight --syntax=js --style=solarized-light --out-format=rtf | pbcopy'

# Docker
alias docker-killall='docker ps -aq --no-trunc | xargs docker rm'

# vim ft=sh
