#!/bin/bash

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi # rbenv init
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi # pyenv init
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi # pyenv-virtualenv init
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PGDATA=/usr/local/var/postgres
export PGHOST=localhost
export PATH=/usr/local/bin:/usr/local/sbin:~/.cask/bin:~/.bin:$PATH

export ALTERNATE_EDITOR=emacs EDITOR=emacsclient VISUAL=emacsclient
export GIT_EDITOR=/usr/local/bin/emacsclient

export HISTCONTROL=ignoredups
shopt -s histappend

export LANG=en_US.UTF-8

# pass <C-s> and other terminal keys to vim
stty -ixon

if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

setup_teamocil_autocompletion() {
  complete -W "$(teamocil --list)" teamocil
}

if which teamocil >> /dev/null; then
  setup_teamocil_autocompletion
else
  gem install teamocil
  setup_teamocil_autocompletion
fi

export GIT_DUET_GLOBAL=true

# bash-it
export BASH_IT="$HOME/.bash_it"
export BASH_IT_THEME='bobby'
export THEME_CLOCK_CHECK=false
export THEME_BATTERY_PERCENTAGE_CHECK=false
source $BASH_IT/bash_it.sh
