#!/usr/bin/env zsh
# Aliases to manage env keys

function export_secrets () {
  for user ($HOME/.secrets/*); do
    if ($user/$1/env) then
      for secret ($user/$1/env/*) {
        export $secret:t="$(<$secret)"
      }
    fi
  done
  export SECRETS_FOR=$1
}

alias secrets_for_development="export_secrets development"
alias secrets_for_production="export_secrets production"

# vim: ft=sh
